/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numberprinter;

import java.util.concurrent.*;

public class App {
    private ArrayBlockingQueue<Integer> queue = new ArrayBlockingQueue<>(100);
    private ExecutorService printingService = Executors.newFixedThreadPool(10);

    public void printNumbers() {
        for ( int i = 0; i < 100 ; i ++ ) {
            queue.add(i);
        }

        for ( int i = 0; i < 10 ; i++ ) {
            try {
                printingService.execute(new Printer( queue ));
            }
            catch ( Exception error )
            {
                System.out.println(error);
            }

        }

        printingService.shutdown();
    }

    public static void main(String[] args) {
        new App().printNumbers();
    }
}
